name = "FlyThroughPaths"
uuid = "c11bb9a7-2755-425a-88f3-ebe93bbdb91f"
authors = ["Tim Holy <tim.holy@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
FlyThroughPathsMakieExt = "Makie"

[compat]
LinearAlgebra = "1"
Makie = "0.21"
StaticArrays = "1"
Test = "1"
julia = "1.10"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "Test"]
